Repository tchapgouv/tchap-android, pull requests merged in 2022-03, with the labels that each got.

#452 Strandhogg detection
  vector/src/main/AndroidManifest.xml
  vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginActivity.kt
  vector/src/main/java/im/vector/app/core/extensions/Activity.kt
  vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
  vector/src/main/java/im/vector/app/features/lifecycle/VectorActivityLifecycleCallbacks.kt
  vector/src/main/java/im/vector/app/features/login/LoginActivity.kt
  vector/src/main/java/im/vector/app/features/login2/LoginActivity2.kt
Labels: P1, android

#479 Fix room name containing brackets cropped
  changelog.d/479.bugfix
  vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt
  vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItem.kt
Labels: bug, android

#482 Room list is automatically scrolled to the top after opening a room
  changelog.d/481.bugfix
  vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
Labels: android
